
package SwimmingSimulation;

/**
 *@author W.S Mendis
 *This JFrame allows user to delete instance of all person
 *created by user
 */
public class DeleteJFrame extends javax.swing.JFrame {

    /**
     * Creates new form DeleteJFrame
     */
    public DeleteJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PersonCombo = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        MaleButton = new javax.swing.JRadioButton();
        FemaleButton = new javax.swing.JRadioButton();
        JudgeButton = new javax.swing.JRadioButton();
        SpectatorButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel5.setText("Delete");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, 20));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel1.setText("Person:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 70, -1));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel2.setText("Group :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        PersonCombo.setModel(new javax.swing.DefaultComboBoxModel(PeopleTrack.getNameMaleSwimmer()));
        PersonCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonComboActionPerformed(evt);
            }
        });
        getContentPane().add(PersonCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 80, 40));

        buttonGroup1.add(MaleButton);
        MaleButton.setText("Male Swimmer");
        MaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleButtonActionPerformed(evt);
            }
        });
        getContentPane().add(MaleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        buttonGroup1.add(FemaleButton);
        FemaleButton.setText("Female Swimmer");
        FemaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleButtonActionPerformed(evt);
            }
        });
        getContentPane().add(FemaleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        buttonGroup1.add(JudgeButton);
        JudgeButton.setText("Judge");
        JudgeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JudgeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(JudgeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, -1));

        buttonGroup1.add(SpectatorButton);
        SpectatorButton.setText("Spectator");
        SpectatorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpectatorButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SpectatorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, -1, -1));

        setBounds(0, 0, 561, 226);
    }// </editor-fold>//GEN-END:initComponents

    private void PersonComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PersonComboActionPerformed
    // This method updates each list of the combo box according to the removed instance
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println(PersonCombo.getSelectedIndex());
        if(MaleButton.isSelected()){
            PeopleTrack.removeMaleSwimmer(PersonCombo.getSelectedIndex());
            PersonCombo.setModel(new javax.swing.DefaultComboBoxModel(PeopleTrack.getNameMaleSwimmer()));
        }else if(FemaleButton.isSelected()){
            PeopleTrack.removeFemaleSwimmer(PersonCombo.getSelectedIndex());
            PersonCombo.setModel(new javax.swing.DefaultComboBoxModel(PeopleTrack.getNameFemaleSwimmer()));
        }else if(JudgeButton.isSelected()){
            PeopleTrack.removeJudge(PersonCombo.getSelectedIndex());
            PersonCombo.setModel(new javax.swing.DefaultComboBoxModel(PeopleTrack.getNameJudge()));
        }else if(SpectatorButton.isSelected()){
            PeopleTrack.removeSpectator(PersonCombo.getSelectedIndex());
            PersonCombo.setModel(new javax.swing.DefaultComboBoxModel(PeopleTrack.getNameSpectator()));
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    // Following radio buttons sets each combo box to related lists
    private void FemaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleButtonActionPerformed
        PersonCombo.setModel(new javax.swing.DefaultComboBoxModel(PeopleTrack.getNameFemaleSwimmer()));
    }//GEN-LAST:event_FemaleButtonActionPerformed

    private void JudgeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JudgeButtonActionPerformed
        PersonCombo.setModel(new javax.swing.DefaultComboBoxModel(PeopleTrack.getNameJudge()));
    }//GEN-LAST:event_JudgeButtonActionPerformed

    private void MaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleButtonActionPerformed
        PersonCombo.setModel(new javax.swing.DefaultComboBoxModel(PeopleTrack.getNameMaleSwimmer()));
    }//GEN-LAST:event_MaleButtonActionPerformed

    private void SpectatorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpectatorButtonActionPerformed
        PersonCombo.setModel(new javax.swing.DefaultComboBoxModel(PeopleTrack.getNameSpectator()));
    }//GEN-LAST:event_SpectatorButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton FemaleButton;
    private javax.swing.JRadioButton JudgeButton;
    private javax.swing.JRadioButton MaleButton;
    private javax.swing.JComboBox PersonCombo;
    private javax.swing.JRadioButton SpectatorButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
