package SwimmingSimulation;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;


/**
 * @author W.S Mendis
 *This JFrame allows user to select event, players, judges to
 * initiate the simulation
 * 
 */
public class IntroJFrame extends javax.swing.JFrame {
    /**
     * Creates new form IntroJFrame
     * @return 
     */
    
    // validates whether the same person is selected twice
    public static boolean condition(){
        return SwimmingCompetetion.validatePlayer()&&SwimmingCompetetion.validateJudge(JudgeCombo1, JudgeCombo2);
    }
    
    public IntroJFrame() {
        initComponents();
    }
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SelectBox = new javax.swing.JComboBox();
        EventBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        NoCombo = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        SwimmerCombo5 = new javax.swing.JComboBox();
        SwimmerCombo1 = new javax.swing.JComboBox();
        SwimmerCombo2 = new javax.swing.JComboBox();
        SwimmerCombo3 = new javax.swing.JComboBox();
        SwimmerCombo4 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        JudgeCombo2 = new javax.swing.JComboBox();
        JudgeCombo1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Setup");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Setup : Simulation");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Event                  :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 150, -1));

        SelectBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Men's", "Women's" }));
        SelectBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SelectBoxItemStateChanged(evt);
            }
        });
        SelectBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectBoxActionPerformed(evt);
            }
        });
        getContentPane().add(SelectBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        EventBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Backstroke", "Breaststroke", "Butterfly Stroke", "Free Style" }));
        EventBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventBoxActionPerformed(evt);
            }
        });
        getContentPane().add(EventBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Select Judges   :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 130, -1));

        NoCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select No.", "2", "3", "4", "5" }));
        NoCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                NoComboItemStateChanged(evt);
            }
        });
        NoCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoComboActionPerformed(evt);
            }
        });
        getContentPane().add(NoCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 110, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("No. of Swimmers :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        SwimmerCombo5.setModel(new javax.swing.DefaultComboBoxModel(PeopleTrack.getNameMaleSwimmer()));
        SwimmerCombo5.setName("ln5"); // NOI18N
        SwimmerCombo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SwimmerCombo5ActionPerformed(evt);
            }
        });
        getContentPane().add(SwimmerCombo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 100, -1));

        SwimmerCombo1.setName("ln1"); // NOI18N
        if(SelectBox.getSelectedIndex()==0){
            SwimmerCombo1.setModel(new javax.swing.DefaultComboBoxModel(PeopleTrack.getNameMaleSwimmer()));
        }
        SwimmerCombo1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SwimmerCombo1ItemStateChanged(evt);
            }
        });
        SwimmerCombo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SwimmerCombo1ActionPerformed(evt);
            }
        });
        getContentPane().add(SwimmerCombo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 100, -1));

        SwimmerCombo2.setModel(new javax.swing.DefaultComboBoxModel(PeopleTrack.getNameMaleSwimmer()));
        SwimmerCombo2.setName("ln2"); // NOI18N
        SwimmerCombo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SwimmerCombo2ActionPerformed(evt);
            }
        });
        getContentPane().add(SwimmerCombo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 100, -1));

        SwimmerCombo3.setModel(new javax.swing.DefaultComboBoxModel(PeopleTrack.getNameMaleSwimmer()));
        SwimmerCombo3.setName("ln3"); // NOI18N
        SwimmerCombo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SwimmerCombo3ActionPerformed(evt);
            }
        });
        getContentPane().add(SwimmerCombo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 100, -1));

        SwimmerCombo4.setModel(new javax.swing.DefaultComboBoxModel(PeopleTrack.getNameMaleSwimmer()));
        SwimmerCombo4.setName("ln4"); // NOI18N
        getContentPane().add(SwimmerCombo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 100, -1));

        jButton1.setText("Simulate");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 90, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Select Palyers      :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 130, -1));

        JudgeCombo2.setModel(new javax.swing.DefaultComboBoxModel(PeopleTrack.getNameJudge()));
        JudgeCombo2.setName("ln5"); // NOI18N
        JudgeCombo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JudgeCombo2ActionPerformed(evt);
            }
        });
        getContentPane().add(JudgeCombo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 100, -1));

        JudgeCombo1.setModel(new javax.swing.DefaultComboBoxModel(PeopleTrack.getNameJudge()));
        JudgeCombo1.setName("ln4"); // NOI18N
        getContentPane().add(JudgeCombo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 100, -1));

        setBounds(0, 0, 411, 461);
    }// </editor-fold>//GEN-END:initComponents

    private void NoComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoComboActionPerformed
    
    /* Following method checks all the validations (whether number of players are selected,
       whether the same person is not selected twice) and send all the information to
       controller class (SwimmingCompetetion) to sort out which players,judges are selected
       to initiate the simulation*/  
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(NoCombo.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null,"Select number of players.");   
        }else{
                Swimming_Simulation ss = new Swimming_Simulation();
                ss.setLanes();

                Swimming_Simulation.initJudge(SwimmingCompetetion.getJudges(JudgeCombo1).get_Name(), SwimmingCompetetion.getJudges(JudgeCombo2).get_Name());
                SwimmingCompetetion.assignSeats();
                SwimmingCompetetion.assignSupportStaff();


                if(NoCombo.getSelectedIndex()==1){
                    SwimmingCompetetion.setMovement(SelectBox, EventBox, SwimmerCombo1);
                    SwimmingCompetetion.setMovement(SelectBox, EventBox, SwimmerCombo2);
                }else if(NoCombo.getSelectedIndex()==2){
                    SwimmingCompetetion.setMovement(SelectBox, EventBox, SwimmerCombo1);
                    SwimmingCompetetion.setMovement(SelectBox, EventBox, SwimmerCombo2);
                    SwimmingCompetetion.setMovement(SelectBox, EventBox, SwimmerCombo3);
                }else if(NoCombo.getSelectedIndex()==3){
                    SwimmingCompetetion.setMovement(SelectBox, EventBox, SwimmerCombo1);
                    SwimmingCompetetion.setMovement(SelectBox, EventBox, SwimmerCombo2);
                    SwimmingCompetetion.setMovement(SelectBox, EventBox, SwimmerCombo3);
                    SwimmingCompetetion.setMovement(SelectBox, EventBox, SwimmerCombo4);
                }else{
                    SwimmingCompetetion.setMovement(SelectBox, EventBox, SwimmerCombo1);
                    SwimmingCompetetion.setMovement(SelectBox, EventBox, SwimmerCombo2);
                    SwimmingCompetetion.setMovement(SelectBox, EventBox, SwimmerCombo3);
                    SwimmingCompetetion.setMovement(SelectBox, EventBox, SwimmerCombo4); 
                    SwimmingCompetetion.setMovement(SelectBox, EventBox, SwimmerCombo5); 
                }
                
                if(condition()){
                    ScoreBoard.setTime(System.currentTimeMillis());
                    ss.hideLabel();
                    ss.setVisible(true);
                }else{
                    JOptionPane.showMessageDialog(null,"Player/Judge already assigned.");
                    SwimmingCompetetion.players=new ArrayList<Swimmer>();
                }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed

    }//GEN-LAST:event_jButton1MousePressed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void SwimmerCombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SwimmerCombo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SwimmerCombo1ActionPerformed

    private void SwimmerCombo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SwimmerCombo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SwimmerCombo3ActionPerformed

    private void SwimmerCombo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SwimmerCombo5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SwimmerCombo5ActionPerformed

    private void SwimmerCombo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SwimmerCombo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SwimmerCombo2ActionPerformed
    
    // Following method change the list to be displayed according to chosen option
    private void SelectBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SelectBoxItemStateChanged
        if(SelectBox.getSelectedIndex()==0){
            SwimmerCombo1.setModel(new javax.swing.DefaultComboBoxModel(PeopleTrack.getNameMaleSwimmer()));
            SwimmerCombo2.setModel(new javax.swing.DefaultComboBoxModel(PeopleTrack.getNameMaleSwimmer()));
            SwimmerCombo3.setModel(new javax.swing.DefaultComboBoxModel(PeopleTrack.getNameMaleSwimmer()));
            SwimmerCombo4.setModel(new javax.swing.DefaultComboBoxModel(PeopleTrack.getNameMaleSwimmer()));
            SwimmerCombo5.setModel(new javax.swing.DefaultComboBoxModel(PeopleTrack.getNameMaleSwimmer()));
        }else{
            SwimmerCombo1.setModel(new javax.swing.DefaultComboBoxModel(PeopleTrack.getNameFemaleSwimmer()));
            SwimmerCombo2.setModel(new javax.swing.DefaultComboBoxModel(PeopleTrack.getNameFemaleSwimmer()));
            SwimmerCombo3.setModel(new javax.swing.DefaultComboBoxModel(PeopleTrack.getNameFemaleSwimmer()));
            SwimmerCombo4.setModel(new javax.swing.DefaultComboBoxModel(PeopleTrack.getNameFemaleSwimmer()));
            SwimmerCombo5.setModel(new javax.swing.DefaultComboBoxModel(PeopleTrack.getNameFemaleSwimmer()));
        }
    }//GEN-LAST:event_SelectBoxItemStateChanged

    private void SelectBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectBoxActionPerformed

    // Displays the number of swimmers you can select according to chosen value
    private void NoComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_NoComboItemStateChanged
        if(NoCombo.getSelectedIndex()==1){
            SwimmerCombo1.setVisible(true);
            SwimmerCombo2.setVisible(true);
            SwimmerCombo3.setVisible(false);
            SwimmerCombo4.setVisible(false);
            SwimmerCombo5.setVisible(false);   
        }else if(NoCombo.getSelectedIndex()==2){
            SwimmerCombo1.setVisible(true);
            SwimmerCombo2.setVisible(true);
            SwimmerCombo3.setVisible(true);
            SwimmerCombo4.setVisible(false);
            SwimmerCombo5.setVisible(false);            
        }else if(NoCombo.getSelectedIndex()==3){
            SwimmerCombo1.setVisible(true);
            SwimmerCombo2.setVisible(true);
            SwimmerCombo3.setVisible(true);
            SwimmerCombo4.setVisible(true);
            SwimmerCombo5.setVisible(false); 
        }else{
            SwimmerCombo1.setVisible(true);
            SwimmerCombo2.setVisible(true);
            SwimmerCombo3.setVisible(true);
            SwimmerCombo4.setVisible(true);
            SwimmerCombo5.setVisible(true);
        }
    }//GEN-LAST:event_NoComboItemStateChanged

    private void EventBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EventBoxActionPerformed

    private void JudgeCombo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JudgeCombo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JudgeCombo2ActionPerformed

    private void SwimmerCombo1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SwimmerCombo1ItemStateChanged

    }//GEN-LAST:event_SwimmerCombo1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntroJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntroJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntroJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntroJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntroJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox EventBox;
    private static javax.swing.JComboBox JudgeCombo1;
    private static javax.swing.JComboBox JudgeCombo2;
    private javax.swing.JComboBox NoCombo;
    private javax.swing.JComboBox SelectBox;
    private javax.swing.JComboBox SwimmerCombo1;
    private javax.swing.JComboBox SwimmerCombo2;
    private javax.swing.JComboBox SwimmerCombo3;
    private javax.swing.JComboBox SwimmerCombo4;
    private javax.swing.JComboBox SwimmerCombo5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
