package SwimmingSimulation;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * @author W.S Mendis
 * 
 * Main interface of the GUI which allows user to choose the option
 */
public class Swimming_Competetion_Info extends javax.swing.JFrame {

    /**
     * Creates new form Swimming_Competetion_Info
     */
    public Swimming_Competetion_Info() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        but_set = new javax.swing.JButton();
        but_swim = new javax.swing.JButton();
        but_jud = new javax.swing.JButton();
        but_delete = new javax.swing.JButton();
        but_spec1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Swimming Competetion");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Swimming Competetion");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 10, 400, -1));

        but_set.setText("Setup");
        but_set.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                but_setMousePressed(evt);
            }
        });
        but_set.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_setActionPerformed(evt);
            }
        });
        getContentPane().add(but_set, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 140, 40));

        but_swim.setText("Add Swimmer");
        but_swim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                but_swimMousePressed(evt);
            }
        });
        but_swim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_swimActionPerformed(evt);
            }
        });
        getContentPane().add(but_swim, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 140, 40));

        but_jud.setText("Add Judge");
        but_jud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                but_judMousePressed(evt);
            }
        });
        but_jud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_judActionPerformed(evt);
            }
        });
        getContentPane().add(but_jud, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 140, 40));

        but_delete.setText("Delete");
        but_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                but_deleteMousePressed(evt);
            }
        });
        but_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_deleteActionPerformed(evt);
            }
        });
        getContentPane().add(but_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 140, 40));

        but_spec1.setText("Add Spectator");
        but_spec1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                but_spec1MousePressed(evt);
            }
        });
        but_spec1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_spec1ActionPerformed(evt);
            }
        });
        getContentPane().add(but_spec1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 140, 40));

        setBounds(0, 0, 307, 405);
    }// </editor-fold>//GEN-END:initComponents
    
    //Opens IntroJFram
    private void but_setActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_setActionPerformed
        IntroJFrame ij = new IntroJFrame();
        ij.setVisible(true);
    }//GEN-LAST:event_but_setActionPerformed
    
    //Opens SwimmerJFrame
    private void but_swimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_swimActionPerformed
        SwimmerJFrame sw = new SwimmerJFrame();
        sw.setVisible(true);
    }//GEN-LAST:event_but_swimActionPerformed

    //Opens JudgeJFrame
    private void but_judActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_judActionPerformed
        JudgeJFrame jf = new JudgeJFrame();
        jf.setVisible(true);
    }//GEN-LAST:event_but_judActionPerformed

    //Opens DeleteJFrame
    private void but_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_deleteActionPerformed
        DeleteJFrame dt = new DeleteJFrame();
        dt.setVisible(true);
    }//GEN-LAST:event_but_deleteActionPerformed

    private void but_swimMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but_swimMousePressed

    }//GEN-LAST:event_but_swimMousePressed

    private void but_judMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but_judMousePressed

    }//GEN-LAST:event_but_judMousePressed

    private void but_deleteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but_deleteMousePressed

    }//GEN-LAST:event_but_deleteMousePressed

    private void but_setMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but_setMousePressed

    }//GEN-LAST:event_but_setMousePressed

    private void but_spec1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but_spec1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_but_spec1MousePressed
    
    //Pens spectatorJFrame
    private void but_spec1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_spec1ActionPerformed
        SpectatorJFrame sf = new SpectatorJFrame();
        sf.setVisible(true);
    }//GEN-LAST:event_but_spec1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Swimming_Competetion_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Swimming_Competetion_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Swimming_Competetion_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Swimming_Competetion_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Swimming_Competetion_Info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but_delete;
    private javax.swing.JButton but_jud;
    private javax.swing.JButton but_set;
    private javax.swing.JButton but_spec1;
    private javax.swing.JButton but_swim;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
